# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 221946b09941e6e7c6134dca56684e4cb867120d28c152f624390d229adf5d644a980711c38299eb0e04fe457907e5ea41740500a264860734dd5a95345e55c3
  app_id: <%= ENV["GOOGLE_APP_ID"] %>
  client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  
test:
  secret_key_base: 6511eae001aa6a13422db5ef8f0a4e4724a775d0ec14637003757c564e0d0e80547c60ba74a8c38fa0ecbf4e21b1e072438a798aa197e9c5435a0deae932278c
  app_id: <%= ENV["GOOGLE_APP_ID"] %>
  client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_id: <%= ENV["GOOGLE_APP_ID"] %>
  client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  